services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.8.11.66
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
    environment:
      CLICKHOUSE_DB: example 
      CLICKHOUSE_USER: clickhouse 
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1 
      CLICKHOUSE_PASSWORD: clickhouse

  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #     MINIO_DEFAULT_BUCKETS: raw_events
  #   volumes:
  #     - minio_data:/data
  #   ports:
  #     - "9001:9000"
  #     - "9002:9001"
  #   command: ["server", "/data", "--console-address", ":9001"]
volumes:
  clickhouse_data:
  # minio_data: